//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.26 at 11:12:49 PM CDT 
//


package com.test.producesoap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hit.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="hit"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FLOP"/&gt;
 *     &lt;enumeration value="AVERAGE"/&gt;
 *     &lt;enumeration value="HIT"/&gt;
 *     &lt;enumeration value="SUPERHIT"/&gt;
 *     &lt;enumeration value="BLOCKBUSTER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "hit")
@XmlEnum
public enum Hit {

    FLOP,
    AVERAGE,
    HIT,
    SUPERHIT,
    BLOCKBUSTER;

    public String value() {
        return name();
    }

    public static Hit fromValue(String v) {
        return valueOf(v);
    }

}
