//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.26 at 11:12:49 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://test.com/producesoap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.test.producesoap;
